language: rust
rust:
  - nightly
  
script:
  - rustup target add wasm32-unknown-unknown
  - cargo build --verbose --all
  - cargo test --verbose --all

cache:
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
  - $TRAVIS_BUILD_DIR/test-project-simple/target/debug
  - $TRAVIS_BUILD_DIR/test-project-simple/target/release
  - $TRAVIS_BUILD_DIR/test-project-simple/target/wasm32-unknown-unknown